import React, { useState } from 'react';

import { useDispatch } from 'react-redux';
import { updateLoading } from '../../redux/actions';

import AgentFilter from './AgentFilter';
import AgentResult from './AgentResult';

import '../../style/viewAgents.scss';


const agentData = [
  {
    id: 1,
    name: "Amit Kumar Singh",
    code: "100001",
    mobile: "9080706050",
    email: "amit.singh@maventechlabs.com",
    paymentType: "Online Prepaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "29AABCU9603R1ZJ",
    panno: "ALWPG5809L",
    state: "Andhra Pradesh",
    city: "Hyderabad",
    status: "Active",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2022-01-01",
  },
  {
    id: 2,
    name: "Nisar E",
    code: "100002",
    mobile: "9080706051",
    email: 'nisar.ellakandi@maventechlabs.com',
    paymentType: "Online Postpaid",
    commType: "Routewise",
    bookingVisiblity: "Branch All Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Andhra Pradesh",
    city: "Hyderabad",
    status: "Inactive",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2021-01-01",
  },
  {
    id: 3,
    name: "Krishna Pandey",
    code: "100003",
    mobile: "9080706051",
    email: 'krishna.pandey@maventechlabs.com',
    paymentType: "Online Prepaid",
    commType: "Jackup %",
    bookingVisiblity: "Branch Restricted",
    gstin: "24AABCU9603R1ZT",
    panno: "ALWPG5809L",
    state: "Gujrat",
    city: "Ahmedabad",
    status: "Inactive",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2021-08-11",
  },
  {
    id: 4,
    name: "Sarvesh Verma",
    code: "100004",
    mobile: "9080706051",
    email: 'sarvesh.verma@maventechlabs.com',
    paymentType: "Offline Postpaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Andhra Pradesh",
    city: "Hyderabad",
    status: "Inactive",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2021-05-19",
  },
  {
    id: 5,
    name: "Shaziya Praveen",
    code: "100005",
    mobile: "9080706052",
    email: 'shaziya.praveen@maventechlabs.com',
    paymentType: "Offline Prepaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Maharastra",
    city: "Mumbai",
    status: "Active",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2022-02-21",
  },
  {
    id: 6,
    name: "Sachin Jhadav",
    code: "100006",
    mobile: "9080706053",
    email: 'sachin.jhadav@maventechlabs.com',
    paymentType: "Online Postpaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Maharastra",
    city: "Mumbai",
    status: "Active",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2022-05-22",
  },
  {
    id: 7,
    name: "Vidushi Tiwari",
    code: "100007",
    mobile: "9080706052",
    email: 'vidushi.tiwari@maventechlabs.com',
    paymentType: "Online Prepaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Andhra Pradesh",
    city: "Hyderabad",
    status: "Inactive",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2022-07-15",
  },
  {
    id: 8,
    name: "Pankaj Chandorkar",
    code: "100008",
    mobile: "9080706054",
    email: 'pankaj.chandorkar@maventechlabs.com',
    paymentType: "Offline Postpaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Maharastra",
    city: "Mumbai",
    status: "Inactive",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2022-07-27",
  },
  {
    id: 9,
    name: "Saidesh Dandu",
    code: "100009",
    mobile: "9080706054",
    email: 'saideswara.dandu@maventechlabs.com',
    paymentType: "Offline Prepaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Andhra Pradesh",
    city: "Hyderabad",
    status: "Inactive",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2022-08-25",
  },{
    id: 10,
    name: "Leanne Graham",
    code: "100010",
    mobile: "7707368031",
    email: "Sincere@april.biz",
    paymentType: "Online Prepaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "29AABCU9603R1ZJ",
    panno: "ALWPG5809L",
    state: "Andhra Pradesh",
    city: "Hyderabad",
    status: "Active",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2022-01-01",
  },
  {
    id: 11,
    name: "Ervin Howell",
    code: "100011",
    mobile: "0106926593",
    email: 'Shanna@melissa.tv',
    paymentType: "Online Postpaid",
    commType: "Routewise",
    bookingVisiblity: "Branch All Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Andhra Pradesh",
    city: "Hyderabad",
    status: "Inactive",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2021-01-01",
  },
  {
    id: 12,
    name: "Clementine Bauch",
    code: "100012",
    mobile: "4631234447",
    email: 'Nathan@yesenia.net',
    paymentType: "Online Prepaid",
    commType: "Jackup %",
    bookingVisiblity: "Branch Restricted",
    gstin: "24AABCU9603R1ZT",
    panno: "ALWPG5809L",
    state: "Gujrat",
    city: "Ahmedabad",
    status: "Inactive",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2021-08-11",
  },
  {
    id: 13,
    name: "Patricia Lebsack",
    code: "100013",
    mobile: "4931709623",
    email: 'Julianne.OConner@kory.org',
    paymentType: "Offline Postpaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Andhra Pradesh",
    city: "Hyderabad",
    status: "Inactive",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2021-05-19",
  },
  {
    id: 14,
    name: "Chelsey Dietrich",
    code: "100014",
    mobile: "2549541289",
    email: 'Lucio_Hettinger@annie.ca',
    paymentType: "Offline Prepaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Maharastra",
    city: "Mumbai",
    status: "Active",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2022-02-21",
  },
  {
    id: 15,
    name: "Mrs. Dennis Schulist",
    code: "100015",
    mobile: "4779358478",
    email: 'Karley_Dach@jasper.info',
    paymentType: "Online Postpaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Maharastra",
    city: "Mumbai",
    status: "Active",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2022-05-22",
  },
  {
    id: 16,
    name: "Kurtis Weissnat",
    code: "100016",
    mobile: "2100676132",
    email: 'Telly.Hoeger@billy.biz',
    paymentType: "Online Prepaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Andhra Pradesh",
    city: "Hyderabad",
    status: "Inactive",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2022-07-15",
  },
  {
    id: 17,
    name: "Nicholas Runo",
    code: "100017",
    mobile: "5864936943",
    email: 'Sherwood@rosamond.me',
    paymentType: "Offline Postpaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Maharastra",
    city: "Mumbai",
    status: "Inactive",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2022-07-27",
  },
  {
    id: 18,
    name: "Glenna Reichert",
    code: "100018",
    mobile: "7759766794",
    email: 'Chaim_McDermott@dana.io',
    paymentType: "Offline Prepaid",
    commType: "Fixed % or amount",
    bookingVisiblity: "Own Booking",
    gstin: "27AABCU9603R1ZN",
    panno: "ALWPG5809L",
    state: "Andhra Pradesh",
    city: "Hyderabad",
    status: "Inactive",
    balance: "₹ 10000",
    credit: "₹ 5000",
    createdDt: "2022-08-25",
  },
];

function ViewAgents() {

  const dispatch = useDispatch();
  const [agentResult, setAgentResult] = useState([]);

  const getAgentRecords = (agentFilter) => {
    setAgentResult([]);
    dispatch(updateLoading(true));
    setTimeout(() => {
      dispatch(updateLoading(false));
      setAgentResult(agentData);
    }, 500);
  }

  return (
    <div className='viewAgentContainer'>
      <AgentFilter handelSearchBtnClick={getAgentRecords} />
      {
        agentResult.length > 0 && (
          <AgentResult agentResult={agentResult} />
        )
      }
    </div>
  )
}

export default ViewAgents
